forge "http://forge.puppetlabs.com"

# mod 'puppetlabs/stdlib'

# mod 'ntp',
#   :git => 'git://github.com/puppetlabs/puppetlabs-ntp.git'

mod 'apt',
  :git => 'https://github.com/puppetlabs/puppetlabs-apt.git'
  #:ref => 'feature/master/dans_refactor'

mod 'mysql',
  :git => 'https://github.com/puppetlabs/puppetlabs-mysql.git'

mod 'rabbitmq',
  :git => 'https://github.com/puppetlabs/puppetlabs-rabbitmq.git'
